/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Processes all images in a directory recursively, converting them to WebP format. */
export declare function processDirectory(inputDir: string, outputDir?: string | undefined | null, quality?: number | undefined | null): void
/** Processes all images in a directory recursively, converting them to WebP format and optionally keeping original file names. */
export declare function processDirectoryDestructive(inputDir: string, keepOriginalNames?: boolean | undefined | null, quality?: number | undefined | null): void
/** Converts a buffer containing image data to WebP format with options. */
export declare function convertToWebp(buffer: Buffer, extension: string, options: WebpOptions): Buffer
